# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.wurstclient_v7
archives_name = wurst_client_on_neoforge
enabled_platforms = neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.18.3
neoforge_version = 21.1.215

org.gradle.java.home=C:\\Users\\olive\\.jdks\\jdk-21.0.11+10